### ISSUE TITLE
Map without root posibility

### ISSUE THREAD

**Issue by Sennevds** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera#1]
I've found a fork of Valetudo RE and the guy says he reveresed engineerd the web api off xiaomi to retrieve the map: https://github.com/Xento/valetudo/blob/testing/lib/SmarthomeAPI.js
When I have time I will check if this still works but maybe this is a interesting way to retrieve the map.

Edit:
I've it locally running and it looks like it's working. It gets the latest run map of the robot.
I'm going to try create a basic python script for this to see if I get it working

**Comment by PiotrMachowski** [comment]
That looks great, thanks for your suggestion! Which vacuum do you have? Could you please send a screenshot of a map?

**Comment by Sennevds** [comment]
I have the s5
this is what it looks like:
![image](https://user-images.githubusercontent.com/3531609/73922395-6185b380-48c9-11ea-9708-a07115d5b4f0.png)

**Comment by Sennevds** [comment]
I'm trying to recreate this in python and I can succefully login but the getmapurl is failing(returns 401)
I think it's because of my body I send(the headers look fine)Do you have experience with creating buffers and hashes in python? 

Edit:
Here's my first try(it's quiet ugly just to get it working) https://github.com/Sennevds/xiaomi_vacuum_map
Like I said I can login but then I can't get the authentication to work

**Comment by PiotrMachowski** [comment]
My Python experience is limited to HA related stuff, but I am not afraid of doing some research.
I was planning to rewrite it as a custom component, but I haven't started it yet. Do you share your code somewhere? Maybe we'll figure it out together

**Comment by PiotrMachowski** [comment]
A version of map camera that does not require root is available [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor)
