### ISSUE TITLE
Log warning about width and height

### ISSUE THREAD

**Issue by rschuiling** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera#5]
I'm getting this warning in the log:
"The camera entity camera.xiaomi_cloud_map_extractor does not support requesting width and height, please open an issue with the integration author"

So here is the issue ;-)

This is on HA Core 2021.12.5 / Xiaomi Vacuum Map Extractor v2.1.1.

**Comment by PiotrMachowski** [comment]
Woah, somebody uses this integration 😮

**Comment by rschuiling** [comment]
Or... I just made a mistake and reported the issue in the wrong repository *blushing*
