### ISSUE TITLE
Getting room ids/names?

### ISSUE THREAD

**Issue by fokcuk** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Vacuum-Map-Camera#8]
Hi
Sorry, could not find a discussion page for the integration
I see that it can get the room names and numbers (possibly from the map extractor?)
Do you mind sharing how I can get that info direct out of the vacuum? I tried a few MIOT integrations that suppose to get info via SIID and PIID but I cannot get available room numbers (or at least a total room count)

**Comment by PiotrMachowski** [comment]
That's because you have checked wrong repo

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/discussions/317
